waypoints:
  home:
    x: 0.0
    y: 0.0
    theta: 0.0
  kitchen:
    x: 1.0
    y: 2.0
    theta: 1.57
  table1:
    x: 2.0
    y: -2.0
    theta: 3.14
  table2:
    x: 4.0
    y: -2.0
    theta: 3.14
  table3:
    x: 6.0
    y: -1.0
    theta: 3.14

